import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import styles from "./page.module.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TV shows APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Providers>
              {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
