import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { SidebarNavigation } from "@/components/shared/SidebarNavigation/SidebarNavigation";
import styles from "./page.module.css"
import { Flex } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TV shows APP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className={styles.main}>
          <Providers>
            <Flex flexDirection={["column","column", "row"]}>
              <SidebarNavigation/>
              {children}
            </Flex>
          </Providers>
        </main>
      </body>
    </html>
  );
}
